package ztp.lista1.view;

public enum ViewActionType {
    MAIN_MENU_CHOICE,
    COURSE_MENU_CHOICE, STUDENT_MENU_CHOICE,
    COURSE_CREATE, COURSE_EDIT, COURSE_DELETE,
    STUDENT_CREATE, STUDENT_EDIT, STUDENT_DELETE
}
