package ztp.lista1.model.jdbc;

public enum SQLQueryType {
    INSERT_STUDENT, SELECT_STUDENT, SELECT_STUDENTS, UPDATE_STUDENT, DELETE_STUDENT,
    INSERT_COURSE, SELECT_COURSE, SELECT_COURSES, UPDATE_COURSE, DELETE_COURSE,
}
